=== HolczerVanda/C0LLER_XMLGyak/XMLTaskC0LLER/XMLSchemaC0LLER.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <!-- Collection of simple types and restrections -->

    <xs:element name="date_of_birth" type="xs:date" />
    <xs:element name="age" type="xs:positiveInteger" />
    <xs:element name="phone_number" type="phoneNumberType" />
    <xs:element name="email_address" type="emailAddressType" />
    <xs:element name="written_name" type="xs:string" />
    <xs:element name="date" type="xs:date" />
    <xs:element name="lending_or_taking" type="xs:boolean" />
    <xs:element name="title" type="xs:string" />
    <xs:element name="borrowable" type="xs:boolean" />
    <xs:element name="late_fee" type="xs:integer" />
    <xs:element name="deadline" type="xs:date" />
    <xs:element name="publication_date" type="xs:date" />
    <xs:element name="handing_date" type="xs:date"></xs:element>

    <xs:simpleType name="phoneNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{3}-\d{4}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailAddressType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Complex type and own type definitions -->


    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="city" type="xs:string" />
            <xs:element name="street" type="xs:string" />
            <xs:element name="house_number" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="first_name" type="xs:string" />
            <xs:element name="last_name" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="librarianType">
        <xs:sequence>
            <xs:element name="name" type="nameType" />
            <xs:element ref="date_of_birth" />
            <xs:element ref="age" />
            <xs:element ref="phone_number" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="librarian_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="businessCardType">
        <xs:sequence>
            <xs:element ref="written_name" />
        </xs:sequence>
        <xs:attribute name="card_id" type="xs:integer" use="required" />
        <xs:attribute name="librarian_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="borrowerType">
        <xs:sequence>
            <xs:element name="name" type="nameType" />
            <xs:element ref="date_of_birth" />
            <xs:element ref="age" />
            <xs:element name="address" type="addressType" minOccurs="0" />
            <xs:element ref="phone_number" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="email_address" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="borrower_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="handingOverType">
        <xs:sequence>
            <xs:element ref="handing_date" minOccurs="0" />
            <xs:element ref="lending_or_taking" />
        </xs:sequence>
        <xs:attribute name="book_id" type="xs:integer" use="required" />
        <xs:attribute name="librarian_id" type="xs:integer" use="required" />
        <xs:attribute name="borrower_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element ref="title" />
            <xs:element ref="borrowable" />
        </xs:sequence>
        <xs:attribute name="book_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="borrowedByType">
        <xs:sequence>
            <xs:element ref="late_fee" />
            <xs:element ref="deadline" />
        </xs:sequence>
        <xs:attribute name="book_id" type="xs:integer" use="required" />
        <xs:attribute name="borrower_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="authorType">
        <xs:sequence>
            <xs:element name="name" type="nameType" />
            <xs:element ref="date_of_birth" />
            <xs:element ref="age" />
        </xs:sequence>
        <xs:attribute name="author_id" type="xs:integer" use="required" />
    </xs:complexType>

    <xs:complexType name="writtenByType">
        <xs:sequence>
            <xs:element ref="publication_date" />
        </xs:sequence>
        <xs:attribute name="book_id" type="xs:integer" use="required" />
        <xs:attribute name="author_id" type="xs:integer" use="required" />
    </xs:complexType>

    <!-- Use of the elements from the root element -->

    <xs:element name="C0LLER_Library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="librarian" type="librarianType" minOccurs="3"
                    maxOccurs="unbounded" />
                <xs:element name="business_card" type="businessCardType" minOccurs="3"
                    maxOccurs="unbounded" />
                <xs:element name="borrower" type="borrowerType" minOccurs="3" maxOccurs="unbounded" />
                <xs:element name="handing_over" type="handingOverType" minOccurs="3"
                    maxOccurs="unbounded" />
                <xs:element name="book" type="bookType" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="borrowed_by" type="borrowedByType" minOccurs="0"
                    maxOccurs="unbounded" />
                <xs:element name="author" type="authorType" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="written_by" type="writtenByType" minOccurs="0"
                    maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!-- Unique keys -->

        <xs:key name="business_card_key">
            <xs:selector xpath="business_card" />
            <xs:field xpath="@card_id" />
        </xs:key>

        <xs:key name="librarian_key">
            <xs:selector xpath="librarian" />
            <xs:field xpath="@librarian_id" />
        </xs:key>

        <xs:key name="handing_over_key">
            <xs:selector xpath="handing_over" />
            <xs:field xpath="@book_id" />
        </xs:key>

        <xs:key name="borrower_key">
            <xs:selector xpath="borrower" />
            <xs:field xpath="@borrower_id" />
        </xs:key>

        <xs:key name="book_key">
            <xs:selector xpath="book" />
            <xs:field xpath="@book_id" />
        </xs:key>

        <xs:key name="author_key">
            <xs:selector xpath="author" />
            <xs:field xpath="@author_id" />
        </xs:key>

        <!-- Foreign keys -->

        <xs:keyref name="business_card_librarian_key" refer="librarian_key">
            <xs:selector xpath="business_card" />
            <xs:field xpath="@librarian_id" />
        </xs:keyref>

        <xs:keyref name="handing_over_librarian_key" refer="librarian_key">
            <xs:selector xpath="handing_over" />
            <xs:field xpath="@librarian_id" />
        </xs:keyref>

        <xs:keyref name="handing_over_borrower_key" refer="borrower_key">
            <xs:selector xpath="handing_over" />
            <xs:field xpath="@borrower_id" />
        </xs:keyref>

        <xs:keyref name="borrowed_by_borrower_key" refer="borrower_key">
            <xs:selector xpath="borrowed_by" />
            <xs:field xpath="@borrower_id" />
        </xs:keyref>

        <xs:keyref name="borrowed_by_book_key" refer="book_key">
            <xs:selector xpath="borrowed_by" />
            <xs:field xpath="@book_id" />
        </xs:keyref>

        <xs:keyref name="written_by_book_key" refer="book_key">
            <xs:selector xpath="written_by" />
            <xs:field xpath="@book_id" />
        </xs:keyref>

        <xs:keyref name="written_by_author_key" refer="author_key">
            <xs:selector xpath="written_by" />
            <xs:field xpath="@author_id" />
        </xs:keyref>

        <!-- 1:1 connection -->
        <xs:unique name="business_card_librarian_oneone">
            <xs:selector xpath="business_card" />
            <xs:field xpath="@librarian_id" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== HolczerVanda/C0LLER_XMLGyak/XMLTaskC0LLER/XMLC0LLER.xml
<?xml version="1.0" encoding="UTF-8"?>
<C0LLER_Library xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="XMLSchemaC0LLER.xsd">

    <!-- Librarian instances -->

    <librarian librarian_id="01">
        <name>
            <first_name>Klaudia</first_name>
            <last_name>Fehér</last_name>
        </name>
        <date_of_birth>2000-05-17</date_of_birth>
        <age>23</age>
        <phone_number>0630-080-8126</phone_number>
        <phone_number>0620-871-4015</phone_number>
    </librarian>

    <librarian librarian_id="02">
        <name>
            <first_name>Albert</first_name>
            <last_name>Pintér</last_name>
        </name>
        <date_of_birth>1988-12-17</date_of_birth>
        <age>35</age>
        <phone_number>0620-155-0102</phone_number>
    </librarian>

    <librarian librarian_id="03">
        <name>
            <first_name>Erzsébet</first_name>
            <last_name>Farkas</last_name>
        </name>
        <date_of_birth>1966-03-12</date_of_birth>
        <age>57</age>
        <phone_number>0670-440-8020</phone_number>
    </librarian>


    <!-- Business card instances -->

    <business_card card_id="11" librarian_id="01">
        <written_name>Fehér Klaudia</written_name>
    </business_card>

    <business_card card_id="12" librarian_id="02">
        <written_name>Pintér Albert</written_name>
    </business_card>

    <business_card card_id="13" librarian_id="03">
        <written_name>Farkas Erzsébet</written_name>
    </business_card>

    <!-- Borrower instances -->

    <borrower borrower_id="21">
        <name>
            <first_name>Árpád</first_name>
            <last_name>Jakab</last_name>
        </name>
        <date_of_birth>1965-01-12</date_of_birth>
        <age>58</age>
        <address>
            <city>Miskolc</city>
            <street>Vitéz utca</street>
            <house_number>31</house_number>
        </address>
        <phone_number>0630-651-4518</phone_number>
        <phone_number>0670-749-3819</phone_number>
    </borrower>

    <borrower borrower_id="22">
        <name>
            <first_name>Georgina</first_name>
            <last_name>Somogyi</last_name>
        </name>
        <date_of_birth>1972-10-24</date_of_birth>
        <age>51</age>
        <address>
            <city>Arnót</city>
            <street>Kisfaludy utca</street>
            <house_number>17</house_number>
        </address>
        <phone_number>0620-845-4708</phone_number>
        <email_address>somogyigeorgina@citromail.hu</email_address>
    </borrower>

    <borrower borrower_id="23">
        <name>
            <first_name>Maja</first_name>
            <last_name>Rácz</last_name>
        </name>
        <date_of_birth>2000-11-28</date_of_birth>
        <age>23</age>
        <email_address>rmaja@freemail.hu</email_address>
    </borrower>

    <!-- Handing over switchboard instances -->

    <handing_over book_id="32" librarian_id="02" borrower_id="21">
        <lending_or_taking>1</lending_or_taking>
    </handing_over>

    <handing_over book_id="31" librarian_id="03" borrower_id="22">
        <handing_date>2023-08-23</handing_date>
        <lending_or_taking>1</lending_or_taking>
    </handing_over>

    <handing_over book_id="33" librarian_id="01" borrower_id="23">
        <handing_date>2022-12-16</handing_date>
        <lending_or_taking>0</lending_or_taking>
    </handing_over>

    <!-- Book instances -->

    <book book_id="31">
        <title> Harry Potter és a Bölcsek Köve</title>
        <borrowable>1</borrowable>
    </book>

    <book book_id="32">
        <title> Ahol a folyami rákok énekelnek</title>
        <borrowable>1</borrowable>
    </book>

    <book book_id="33">
        <title> Fordulópont</title>
        <borrowable>1</borrowable>
    </book>

    <!-- Borrowed by switchboard instances -->

    <borrowed_by book_id="32" borrower_id="21">
        <late_fee>0</late_fee>
        <deadline>2023-03-17</deadline>
    </borrowed_by>

    <borrowed_by book_id="31" borrower_id="22">
        <late_fee>0</late_fee>
        <deadline>2023-09-01</deadline>
    </borrowed_by>

    <borrowed_by book_id="33" borrower_id="23">
        <late_fee>800</late_fee>
        <deadline>2023-02-16</deadline>
    </borrowed_by>

    <!-- Author instances -->

    <author author_id="41">
        <name>
            <first_name>Joanne</first_name>
            <last_name>Rowling</last_name>
        </name>
        <date_of_birth>1965-07-31</date_of_birth>
        <age>58</age>
    </author>

    <author author_id="42">
        <name>
            <first_name>Delia</first_name>
            <last_name>Owens</last_name>
        </name>
        <date_of_birth>1949-04-04</date_of_birth>
        <age>74</age>
    </author>

    <author author_id="43">
        <name>
            <first_name>Danielle</first_name>
            <last_name>Steel</last_name>
        </name>
        <date_of_birth>1965-07-31</date_of_birth>
        <age>58</age>
    </author>

    <!-- Written by switchboard instances -->

    <written_by book_id="31" author_id="41">
        <publication_date>2001-12-13</publication_date>
    </written_by>

    <written_by book_id="32" author_id="42">
        <publication_date>2018-08-14</publication_date>
    </written_by>

    <written_by book_id="33" author_id="43">
        <publication_date>2019-07-21</publication_date>
    </written_by>

</C0LLER_Library>
